<?php

namespace Faker\Provider;

class Department extends \Faker\Provider\Base
{
    protected static $deptList = [
        'ART',
        'CHIN',
        'CRWR',
        'ELIC',
        'EMAF',
        'ENGL',
        'ESLG',
        'FREN',
        'GERM',
        'GNML',
        'HUMN',
        'JAPN',
        'JRNM',
        'MUSC',
        'PHIL',
        'RUSS',
        'SPAN',
        'THTR',
        'ACCT',
        'AOMG',
        'BADM',
        'BUED',
        'CTED',
        'DSCI',
        'FINC',
        'HSAD',
        'HUMR',
        'IBUS',
        'MGMT',
        'MISC',
        'MKED',
        'MKTG',
        'OPSM',
        'PADM',
        'PLAN',
        'PTED',
        'ATTR',
        'CEDP',
        'COIN',
        'EDUC',
        'EXSC',
        'HLED',
        'LBSC',
        'PHED',
        'RCLS',
        'ANTH',
        'CMST',
        'CRIM',
        'CSBS',
        'ECON',
        'GEOG',
        'GOVT',
        'HIST',
        'ITGS',
        'INST',
        'ITDS',
        'PSYC',
        'ROTC',
        'SOCI',
        'SOST',
        'WMST',
        'ASL',
        'BIOL',
        'CHEM',
        'CPLA',
        'CSCD',
        'CSED',
        'DNHY',
        'ENGR',
        'ENVS',
        'FNDT',
        'GEOL',
        'MATH',
        'NTSC',
        'NURS',
        'OCTH',
        'PHTH',
        'PHYS',
        'SCED',
        'TECH',
        'AAST',
        'ADST',
        'AGST',
        'CHST',
        'DSST',
        'IDST',
        'SOWK'];

    /**
     * @example 'CSCD'
     * @return string
     */
    public static function departmentCode()
    {
        return static::randomElement(static::$deptList);
    }
}
